# FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.18
# # 日本語をあつかうときに使うプラグイン
# RUN bin/elasticsearch-plugin install analysis-kuromoji
FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.18
# 日本語をあつかうときに使うプラグイン
RUN bin/elasticsearch-plugin install analysis-kuromoji